### ISSUE TITLE
GO Exception on Launch

### ISSUE THREAD

**Issue by joshuaballas** [ianmarmour/nvidia-clerk#54]
I am getting this stacktrace whenever I download the .exe, place it on my desktop, and Admin CMD to launch the app with `nvidia-clerk-windows.exe -region=USA -test`

```
Exception 0xc0000005 0x0 0x7ff855172fff 0x237b6ff0000
PC=0x237b6ff0000

syscall.Syscall6(0x7ff854396600, 0x6, 0x2, 0x1, 0x0, 0x0, 0x0, 0x81, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/syscall_windows.go:201 +0xf2
internal/syscall/windows.WSASocket(0x100000002, 0x0, 0x0, 0x8100000000, 0xc000359260, 0x30, 0x30)
        /opt/hostedtoolcache/go/1.15.2/x64/src/internal/syscall/windows/zsyscall_windows.go:122 +0xcc
net.sysSocket(0x2, 0x1, 0x0, 0x1401aa0, 0xcb314b, 0xc0000314b0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/sock_windows.go:20 +0x66
net.socket(0x110f240, 0xc00019da40, 0x106e139, 0x3, 0x2, 0x1, 0x0, 0x0, 0x1110140, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/sock_posix.go:19 +0x65
net.internetSocket(0x110f240, 0xc00019da40, 0x106e139, 0x3, 0x1110140, 0x0, 0x1110140, 0xc000359260, 0x1, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/ipsock_posix.go:141 +0x170
net.(*sysDialer).doDialTCP(0xc000038b00, 0x110f240, 0xc00019da40, 0x0, 0xc000359260, 0xfe7020, 0x1401968, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/tcpsock_posix.go:65 +0xc9
net.(*sysDialer).dialTCP(0xc000038b00, 0x110f240, 0xc00019da40, 0x0, 0xc000359260, 0xc000134b48, 0xb559e5, 0x60)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/tcpsock_posix.go:61 +0xde
net.(*sysDialer).dialSingle(0xc000038b00, 0x110f240, 0xc00019da40, 0x110c5c0, 0xc000359260, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:580 +0x5e5
net.(*sysDialer).dialSerial(0xc000038b00, 0x110f240, 0xc00019da40, 0xc00006f3f0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:548 +0x15e
net.(*Dialer).DialContext(0x13ce760, 0x110f240, 0xc00019da40, 0x106e139, 0x3, 0xc0003684b5, 0xf, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:425 +0x6f7
github.com/gobwas/ws.Dialer.dial(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/gobwas/ws@v1.0.4/dialer.go:226 +0x19b
github.com/gobwas/ws.Dialer.Dial(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/gobwas/ws@v1.0.4/dialer.go:165 +0x190
github.com/gobwas/ws.Dial(...)
        /home/runner/go/pkg/mod/github.com/gobwas/ws@v1.0.4/dialer.go:47
github.com/chromedp/chromedp.DialContext(0x110f240, 0xc00019da40, 0xc0003684b0, 0x4a, 0xc000135448, 0x1, 0x1, 0x0, 0xc00007a040, 0xc000135534)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/conn.go:59 +0xb8
github.com/chromedp/chromedp.NewBrowser(0x110f280, 0xc000359170, 0xc0003684b0, 0x4a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/browser.go:104 +0x285
github.com/chromedp/chromedp.(*ExecAllocator).Allocate(0xc00007c140, 0x110f280, 0xc000359170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/allocate.go:240 +0xc1c
github.com/chromedp/chromedp.Run(0x110f280, 0xc000359170, 0xc000135848, 0x3, 0x3, 0x0, 0x1108ee0)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/chromedp.go:227 +0x1f7
github.com/ianmarmour/nvidia-clerk/internal/browser.StartSession(0x106e9eb, 0x5, 0x106e05b, 0x3, 0x1f4, 0x107091d, 0xa, 0x1070913, 0xa, 0x0, ...)
        /home/runner/work/nvidia-clerk/nvidia-clerk/internal/browser/browser.go:167 +0x3d6
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:105 +0x538

goroutine 6 [chan receive]:
github.com/chromedp/chromedp.NewContext.func1(0x110f280, 0xc000359170, 0xc00014cb00)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/chromedp.go:129 +0x7f
created by github.com/chromedp/chromedp.NewContext
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/chromedp.go:128 +0x24d

goroutine 7 [select]:
os/exec.(*Cmd).Start.func2(0xc000158420)
        /opt/hostedtoolcache/go/1.15.2/x64/src/os/exec/exec.go:449 +0xd5
created by os/exec.(*Cmd).Start
        /opt/hostedtoolcache/go/1.15.2/x64/src/os/exec/exec.go:448 +0x751

goroutine 8 [chan receive]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2(0x110f280, 0xc000359170, 0xc000158420, 0xc000158401, 0xc00035aac0, 0x3d, 0xc00014cb00, 0xc00007c140)
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/allocate.go:199 +0x53
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
        /home/runner/go/pkg/mod/github.com/chromedp/chromedp@v0.5.3/allocate.go:198 +0x9b8
rax     0x7ff8516ed84a
rbx     0x7ff8516ed848
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x237b6d34e40
rsp     0xd3231fead0
r8      0x94b
r9      0x94b
r10     0x94b
r11     0x94b
r12     0x7ff854f80000
r13     0x0
r14     0x7ff8516ed84a
r15     0xc000007a
rip     0x237b6ff0000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by ianmarmour** [comment]
Do you have Chrome installed?

**Comment by ianmarmour** [comment]
Also is this firewalled off from localhost (if you know), this is the first type of exception like this I've seen anybody encounter must be something specific to your host.

**Comment by joshuaballas** [comment]
I do have Chrome installed and I run on a home PC.

**Comment by ianmarmour** [comment]
What version of Chrome specifically? (I'm wondering if it's too old)

**Comment by ianmarmour** [comment]
Also if you have an antivirus are there any warnings/errors there?

**Comment by joshuaballas** [comment]
![image](https://user-images.githubusercontent.com/17985542/93954685-38147d80-fd1c-11ea-9e73-198d8a476983.png)

**Comment by joshuaballas** [comment]
I've disabled all of my antivirus and it still happens.

**Comment by ianmarmour** [comment]
You're running on a typical desktop correct?

Also what command are you using to run this? 

What version of windows are you on also?

**Comment by joshuaballas** [comment]
`./nvidia-clerk-windows.exe -region=USA -test`

Windows 10.

Im a developer too so everything is latest and greatest.

**Comment by ianmarmour** [comment]
Not a ton to go off, are you running on ARM or X86 based system? It's a long shot but worth verifying as it's compiled for 64bit X86 specifically.

**Comment by joshuaballas** [comment]
64 bit

**Comment by ianmarmour** [comment]
Can you confirm by going to cmd.exe that google-chrome can launch from there using that command.

I would think it's either A your Chrome.exe isn't on your path from some reason (easy fix re-install, hard fix add it to your path yourself), B it's somehow a bug in golang (unlikely) or C you have a hardware failure of some kind (unlikely but possible)

**Comment by joshuaballas** [comment]
Chrome opens just fine but it just stays white due to this error and I definitely don't have any hardware failures.

**Comment by joshuaballas** [comment]
There is no PATH environment variable for Chrome. Is this needed? Chrome never added one by default.

**Comment by ianmarmour** [comment]
Yep but it shouldn't be able to launch chrome at all if that was the case....

see https://github.com/ianmarmour/nvidia-clerk/issues/46 for an example.

**Comment by joshuaballas** [comment]
![image](https://user-images.githubusercontent.com/17985542/93955958-f5a07000-fd1e-11ea-80cf-83e7f1395644.png)
This is what happens when I run the command.

**Comment by ianmarmour** [comment]
Yeah it's not your chrome or chrome related then, do you have some sort of firewall blocking local communication? (This tool uses localhost:{EPHERMAL_PORT_NUMBER} to connect to the chrome instance

**Comment by joshuaballas** [comment]
I checked on netstat to see if I had a ton of ports eaten up but I don't. All those ports are open.

**Comment by joshuaballas** [comment]
Any update on this? I was given a custom script elsewhere and it works fine, so I assume it is related to this project and not my pc.

**Comment by joshuaballas** [comment]
I restarted my firewall and its working now, so I have no idea what that was about...
