### ISSUE TITLE
Segfault on version 2.1 (MacOS)

### ISSUE THREAD

**Issue by adrienlemasle** [ianmarmour/nvidia-clerk#59]
./nvidia-clerk-darwin -region=GBR -sms -model=3080
2020/09/23 11:36:08 Erorr unmarshalling inventory XML
2020/09/23 11:36:08 Error getting Product Information retrying...
2020/09/23 11:36:09 Product ID: 5438792800
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x144cf18]

goroutine 1 [running]:
main.MonitorRelease(0x15c5de0, 0xc0001940f0, 0xc000196000, 0x1)
	/home/runner/work/nvidia-clerk/nvidia-clerk/main.go:164 +0x238
main.main()
	/home/runner/work/nvidia-clerk/nvidia-clerk/main.go:96 +0x626

**Comment by adrienlemasle** [comment]
My bad. It looks like I had actually picked version 2.0. I cannot reproduce with 2.1.
